# Vectra brain API access.
vectra:
  url: 'https://<BRAIN_FQDN>/'
  api_token: 'youneedanapikeyheregetonefromyourprofile'  # Please ensure read access to this file is limited

# LDAP configuration
ldap:
  url: 'ldaps://<LDAP_Server>'
  base_dn: 'DC=domain,DC=local'
  ldap_user: 'cn=user,ou=test,dc=domain,dc=local'
  ldap_password: 'Secret' # Please ensure read access to this file is limited

# Logging configuration
log: 
  log_to_file: False
  log_file: 'vectra_ad_groups.log'
  log_backups: 5 # Log files are automatically rotated daily